export * from './Chat/ChatMessage'
export * from './Chat/ChatMessages'
export * from './LeftSidebar/FriendItemShort'
export * from './LeftSidebar/FriendItem'
export * from './LeftSidebar/AnimatedSider'
export * from './RightSidebar/ProfileStatus'
export * from './RightSidebar/TopWriter'
export * from './RightSidebar/ProfileInfoMain'
export * from './RightSidebar/AuthData'
export * from './RightSidebar/SocialMediaContact'
export * from './AddPostForm/AddPost'
export * from './Errors/ErrorPage'

export {default as ProfileInfo} from './RightSidebar/ProfileInfo'