declare module 'authReducer'
declare module "*.module.css"
declare module "*.module.scss"
declare module "*.png"
declare module "*.gif"
declare module "*.jpg"
declare module "*.svg"
declare module 'react-syntax-highlighter'
declare module 'react-syntax-highlighter/dist/esm/styles/prism'